### ISSUE TITLE
npm ERR! 404 Not Found: webpack-log@latest using verdaccio

### ISSUE THREAD

**Issue by slillo** [webpack-contrib/webpack-log#13]
today I'm not able to install webpack-log using:

npm i -D webpack-log

npm ERR! code E404
npm ERR! 404 Not Found: webpack-log@latest

I don't have any problem with other packages. Find this problem installing webpack-dev-server.

I'm using verdaccio I needed to execute:

`npm set registry https://registry.npmjs.org/ && npm i -D webpack-dev-server && npm set registry http://localregisty:4873/`

**Comment by alexander-akait** [comment]
@slillo looks some problem with `npm` register, package exists https://www.npmjs.com/package/webpack-log, try to remove cache `npm cache clear --force`
