### ISSUE TITLE
Issue with name decoration on Linux

### ISSUE THREAD

**Issue by oles** [webpack-contrib/webpack-log#2]
Narrowed it down to: https://github.com/webpack-contrib/webpack-log/blob/9e215a07efa0a0a069b27c30291652241c0f4c82/index.js#L24

The square-thingy that's being used there appears like this when using `webpack-serve`:

![screenshot from 2018-05-15 16-00-39](https://user-images.githubusercontent.com/7634050/40061689-cfc27ca0-5859-11e8-9717-1a480aa76b06.png)

Perhaps a different symbol (or none at all) is better for cross platform?

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.

**Comment by oles** [comment]
Uh-oh! But I didn't remove it! I simply clicked the line -> three dots -> Open new issue

**Comment by oles** [comment]
Opened it correctly over at https://github.com/webpack-contrib/webpack-log/issues/3 :+1:

**Comment by shellscape** [comment]
Hm. Perhaps we've encountered a rare Github bug? In any case, thanks for opening a new one. I have a service running that snipes issues without templates automagically.

**Comment by oles** [comment]
Could be! Anyway - I understand that very well, impossible to handle OSS of such scale as this without :+1:
