### ISSUE TITLE
Issue with name decoration (unicode) on Arch Linux

### ISSUE THREAD

**Issue by oles** [webpack-contrib/webpack-log#3]
* Operating System: Arch Linux, kernel 4.16.7, running Cinnamon 3.8.2, using `ttf-inconsolata` for monospace
* Node Version: 8.11.1
* NPM Version: 6.0.1
* webpack Version: 4.8.3
* webpack-serve Version: 1.0.2

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

https://github.com/webpack-contrib/webpack-log/blob/9e215a07efa0a0a069b27c30291652241c0f4c82/index.js#L24

### Expected Behavior
For it to look pretty! :heart: 

### Actual Behavior
Looks broken :cry: 

![screenshot from 2018-05-15 16-00-39](https://user-images.githubusercontent.com/7634050/40061689-cfc27ca0-5859-11e8-9717-1a480aa76b06.png)

### For Bugs; How can we reproduce the behavior?
Run `webpack-serve` inside a default terminal on Linux (same error in GNOME Terminal 3.28.1, for example)

<br>

Perhaps a different symbol (or none at all) is better for cross platform?

**Comment by shellscape** [comment]
Thanks for the issue :beer:

So the info you snipped at the top is actually there for a good reason. The OS info would have been super useful. Please  please please don't pick and choose which portions of the templates to keep around - that general rule of thumb applies to the entire `webpack-contrib` org and every repo in it.

It looks like your environment is just lacking unicode support, or the default font you have set doesn't support that range. Either of those would be super weird, so get that info updated and we'll go from there.

**Comment by oles** [comment]
I'm not sure what I was thinking. Of course that info is highly relevant here - sorry!

**Comment by shellscape** [comment]
thanks for adding the OS info. I'll dig up the unicode values for those characters and do some digging as to why those aren't showing properly. It's super strange for any system these days to have those characters out of range (they've been around a long time). Do you know off hand which font your terminal(s) is using by default there?

**Comment by oles** [comment]
Strange indeed! Ohyes - I'm still rocking Inconsolata:

![screenshot from 2018-05-15 17-25-21](https://user-images.githubusercontent.com/7634050/40066766-21132eaa-5865-11e8-9121-e41237282ad7.png)

**Comment by oles** [comment]
Tried switching to various other fonts, notably DejaVu Sans Mono as well, but all of them are borked :thinking:

**Comment by shellscape** [comment]
I'm seeing all kinds of "unicode not displaying" issues with *nix flavors and various consoles. Do you know off hand which terminal app you're using there (or which comes default with your distro)? I ask because I'm not that adept at *nix and trying to drill down the search.

**Comment by oles** [comment]
I thought it was just something wrong with the built-in terminal in Emacs... But to be sure I checked using GNOME terminal as well (the default terminal in Ubuntu, for example). 

When it didn't work there either, I figured out it may be a problem for more *nix peeps than those running Arch.

The about window of it reports `GNOME Terminal 3.28.1`

**Comment by shellscape** [comment]
Cool, that should help narrow down the results. Could it by a [non-utf8 locale setting](https://bbs.archlinux.org/viewtopic.php?pid=1299505#p1299505) by chance?

**Comment by oles** [comment]
Seems to be all fine: 

![screenshot from 2018-05-15 17-46-49](https://user-images.githubusercontent.com/7634050/40068078-04655532-5868-11e8-91ed-5c9b300302fc.png)

**Comment by oles** [comment]
Aha - there we have it! 
>https://bbs.archlinux.org/viewtopic.php?pid=1462574#p1462574

`pacman -S ttf-droid`

Then, ta-da: 
![screenshot from 2018-05-15 17-52-03](https://user-images.githubusercontent.com/7634050/40068378-c104d6c2-5868-11e8-9fae-5d0e73afa60a.png)

**Comment by shellscape** [comment]
Ah, wonderful. Thanks for contributing that fix. I'll add that to the README when I get the chance.

Also possibly relevant for anyone happening across this thread:

>This is perhaps relevant: https://github.com/google/fonts/issues/207#issuecomment-179990793
>
>Doesn't look like Inconsolata supports much of a unicode range at all. Also looks like this has been an issue with the font [since 2016](https://github.com/scalameta/scalafmt/issues/277#issuecomment-227578798)

**Comment by oles** [comment]
Seeing it's such a niche problem, it'll just be noise in the readme, unless you write it more generally for people with font problems. 

Big thanks to you as well for taking the time :+1: 

Sad to see Inconsolata growing old and weary. Been with me all this time... 


In case anyone stumbles on in here in the future - just make sure you've installed your recommened fonts (which in this case are listed at https://wiki.archlinux.org/index.php/general_recommendations#Fonts)
